### ISSUE TITLE
In Node js, TypeError: xml.trim is not a function

### ISSUE THREAD

**Issue by Davetwo** [chrisbottin/xml-formatter#40]
In Node I get error
TypeError: xml.trim is not a function

2021-11-08T15:59:45:     at parse (/app/private_deployments/david/consent_api_david_1/node_modules/xml-parser-xo/index.js:238:15)
2021-11-08T15:59:45:     at format (/app/private_deployments/david/consent_api_david_1/node_modules/xml-formatter/index.js:187:23)

**Comment by Davetwo** [comment]
Sorry, the xml passed as parameter was not a string.
